version: '3.7'

services:
  # MongoDB
  cadmus-renovella-mongo:
    image: mongo
    container_name: cadmus-renovella-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --logpath=/dev/null # --quiet
    ports:
      - 27017:27017
    networks:
      - cadmus-renovella-network

  # PostgreSQL
  cadmus-renovella-pgsql:
    image: postgres
    container_name: cadmus-renovella-pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - cadmus-renovella-network
    # volumes:
      # ensure you have created the var/db/pgsql folder in the host
      # https://hub.docker.com/r/postgis/postgis
      # - /var/db/pgsql:/var/lib/postgresql/data

  # Cadmus Renovella API
  cadmus-renovella-api:
    image: vedph2020/cadmus-renovella-api:5.0.1
    container_name: cadmus-renovella-api
    ports:
      # https://stackoverflow.com/questions/48669548/why-does-aspnet-core-start-on-port-80-from-within-docker
      - 40392:8080
    depends_on:
      - cadmus-renovella-mongo
      - cadmus-renovella-pgsql
    environment:
      # for Windows use : as separator, for non Windows use __
      # (see https://github.com/aspnet/Configuration/issues/469)
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-renovella-mongo:27017/{0}
      - CONNECTIONSTRINGS__INDEX=Server=cadmus-renovella-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-renovella-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
      - SEED__INDEXDELAY=25
      - MESSAGING__APIROOTURL=http://cadmusapi.azurewebsites.net
      - MESSAGING__APPROOTURL=http://cadmusapi.com/
      - MESSAGING__SUPPORTEMAIL=support@cadmus.com
      # uncomment if you want to log to a file
      # - SERILOG__LOGPATH=/var/cadmus-log.txt
    # uncomment if you want to bind mount a file-based log
    # volumes:
    #   - /var/cadmus-log.txt:/var/cadmus-log.txt
    networks:
      - cadmus-renovella-network

  # Cadmus Renovella app
  cadmus-renovella-app:
    image: vedph2020/cadmus-renovella-app:5.0.0
    container_name: cadmus-renovella-app
    ports:
      - 4200:80
    depends_on:
      - cadmus-renovella-api
    networks:
      - cadmus-renovella-network

networks:
  cadmus-renovella-network:
    driver: bridge
